# Generated by Django 4.2.30 on 2026-06-20 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belt', models.CharField(choices=[('white', '흰띠'), ('yellow', '노란띠'), ('orange', '주황띠'), ('green', '초록띠'), ('blue', '파란띠'), ('brown', '갈색띠'), ('black1', '검은띠 1단'), ('black2', '검은띠 2단'), ('black3', '검은띠 3단'), ('black4', '검은띠 4단'), ('black5', '검은띠 5단')], max_length=20, verbose_name='띠/단')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필 목록',
            },
        ),
    ]
