# Generated by Django 4.2.30 on 2026-06-20 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='대회명')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='장소')),
                ('organizer', models.CharField(blank=True, max_length=100, verbose_name='주최')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
            ],
            options={
                'verbose_name': '대회 일정',
                'verbose_name_plural': '대회 일정 목록',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('belt', models.CharField(choices=[('white', '흰띠'), ('yellow', '노란띠'), ('orange', '주황띠'), ('green', '초록띠'), ('blue', '파란띠'), ('brown', '갈색띠'), ('black1', '검은띠 1단'), ('black2', '검은띠 2단'), ('black3', '검은띠 3단'), ('black4', '검은띠 4단'), ('black5', '검은띠 5단')], default='white', max_length=20, verbose_name='띠/단')),
                ('weight_class', models.CharField(blank=True, choices=[('u60', '-60kg'), ('u66', '-66kg'), ('u73', '-73kg'), ('u81', '-81kg'), ('u90', '-90kg'), ('u100', '-100kg'), ('o100', '+100kg'), ('u48', '-48kg (여)'), ('u52', '-52kg (여)'), ('u57', '-57kg (여)'), ('u63', '-63kg (여)'), ('u70', '-70kg (여)'), ('u78', '-78kg (여)'), ('o78', '+78kg (여)')], max_length=10, verbose_name='체급')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='연락처')),
                ('join_date', models.DateField(auto_now_add=True, verbose_name='등록일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('start_time', models.TimeField(verbose_name='시작 시간')),
                ('end_time', models.TimeField(verbose_name='종료 시간')),
                ('title', models.CharField(max_length=100, verbose_name='훈련 제목')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='장소')),
                ('description', models.TextField(blank=True, verbose_name='훈련 내용')),
                ('attendees', models.ManyToManyField(blank=True, related_name='trainings', to='schedule.member', verbose_name='참석자')),
            ],
            options={
                'verbose_name': '훈련 일정',
                'verbose_name_plural': '훈련 일정 목록',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_class', models.CharField(blank=True, max_length=20, verbose_name='체급')),
                ('result', models.CharField(choices=[('gold', '금메달'), ('silver', '은메달'), ('bronze', '동메달'), ('participated', '참가'), ('withdrew', '기권')], default='participated', max_length=20, verbose_name='결과')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.competition', verbose_name='대회')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.member', verbose_name='선수')),
            ],
            options={
                'verbose_name': '대회 결과',
                'verbose_name_plural': '대회 결과 목록',
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='competitions', through='schedule.CompetitionResult', to='schedule.member', verbose_name='참가 선수'),
        ),
    ]
