# Generated by Django 4.2.30 on 2026-06-20 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0002_attendanceplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceplan',
            options={'ordering': ['date', 'time_slot'], 'verbose_name': '참석 예정', 'verbose_name_plural': '참석 예정 목록'},
        ),
        migrations.AlterUniqueTogether(
            name='attendanceplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendanceplan',
            name='time_slot',
            field=models.CharField(choices=[('18:00', '오후 6시'), ('19:30', '오후 7시 30분'), ('21:00', '오후 9시')], default='18:00', max_length=5, verbose_name='시간대'),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceplan',
            unique_together={('user', 'date', 'time_slot')},
        ),
    ]
