# Generated by Django 4.2.30 on 2026-06-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_attendanceplan_confirmed_notification_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='belt',
            field=models.CharField(choices=[('white', '흰띠'), ('yellow', '노란띠'), ('orange', '주황띠'), ('green', '초록띠'), ('blue', '파란띠'), ('brown', '갈색띠'), ('black1', '검은띠 1단'), ('black2', '검은띠 2단'), ('black3', '검은띠 3단'), ('black4', '검은띠 4단'), ('black5', '검은띠 5단'), ('black6', '검은띠 6단')], default='white', max_length=20, verbose_name='띠/단'),
        ),
    ]
