# Generated by Django 4.2.30 on 2026-06-21 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_member_belt'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeltPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belt', models.CharField(choices=[('white', '흰띠'), ('yellow', '노란띠'), ('orange', '주황띠'), ('green', '초록띠'), ('blue', '파란띠'), ('brown', '갈색띠'), ('black1', '검은띠 1단'), ('black2', '검은띠 2단'), ('black3', '검은띠 3단'), ('black4', '검은띠 4단'), ('black5', '검은띠 5단'), ('black6', '검은띠 6단')], max_length=20, verbose_name='승급 띠/단')),
                ('promoted_at', models.DateField(verbose_name='승급일')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='메모')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belt_promotions', to='schedule.member', verbose_name='회원')),
            ],
            options={
                'verbose_name': '띠 승급 이력',
                'verbose_name_plural': '띠 승급 이력 목록',
                'ordering': ['-promoted_at'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='연도')),
                ('month', models.IntegerField(verbose_name='월')),
                ('paid', models.BooleanField(default=False, verbose_name='납부 여부')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='납부일')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='메모')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='schedule.member', verbose_name='회원')),
            ],
            options={
                'verbose_name': '회비 납부',
                'verbose_name_plural': '회비 납부 목록',
                'ordering': ['-year', '-month'],
                'unique_together': {('member', 'year', 'month')},
            },
        ),
    ]
