# Generated by Django 4.2.30 on 2026-06-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_beltpromotion_feepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceplan',
            name='time_slot',
            field=models.CharField(choices=[('18:00', '오후 6시'), ('19:30', '오후 7시 30분'), ('21:00', '오후 9시'), ('11:00', '오전 11시'), ('13:00', '오후 1시'), ('15:00', '오후 3시'), ('사유회', '사유회')], default='18:00', max_length=10, verbose_name='시간대'),
        ),
    ]
